package:
  name: ipcoal
  version: '0.0.5'

source:
  url: https://github.com/eaton-lab/ipcoal/archive/0.0.5.tar.gz
  sha256: abd06c47345e2a422453150d72e5a1d0675ee84bdb39ab49accbd655a1e30a43

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  noarch: python
  
requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy >=1.10
    - scipy >=0.10  # can remove soon
    - pandas >=0.16
    - toytree >=1.0.4
    - numba
    - future
    - msprime
    - raxml
    - seq-gen

test:
  imports:
    - ipcoal

about:
  home: http://github.com/eaton-lab/ipcoal
  license: GPLv3
  summary: Interactive and reproducible simulation and analysis of gene trees.
